apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-test2
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  volumeName: nfs-test2
