# This mounts the nfs volume claim into /mnt and continuously
# overwrites /mnt/index.html with the time and hostname of the pod.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-busybox2
spec:
  replicas: 2
  selector:
    matchLabels:
      name: nfs-busybox2
  template:
    metadata:
      labels:
        name: nfs-busybox2
    spec:
      containers:
        - image: busybox
          command:
            - sh
            - -c
            - "while true; do date >> /mnt/index.html; hostname >> /mnt/index.html; sleep $(($RANDOM % 5 + 80)); done"
          imagePullPolicy: IfNotPresent
          name: busybox
          volumeMounts:
            # name must match the volume name below
            - name: nfs-test2
              mountPath: "/mnt"
      volumes:
        - name: nfs-test2
          persistentVolumeClaim:
            claimName: nfs-test2
