apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: linux-od1.home.arpa
    path: "/gv0/mysql"
  mountOptions:
    - nfsvers=4
